services:
  rpc_server.command.router_debug_command:
    class: Bankiru\Api\Rpc\Command\RouterDebugCommand
    arguments:
    - "@rpc_server.router.collection"
    tags:
    - { name: "console.command" }

  rpc_server.controller_resolver:
    class: Bankiru\Api\Rpc\Routing\ControllerResolver\ControllerResolver
    arguments:
    - "@service_container"
    - "@rpc_server.controller_name_parser"
    - "@?logger"

  rpc_server.router.loader:
    class: Bankiru\Api\Rpc\Http\Routing\EndpointRouteLoader
    tags:
    - { name: routing.loader }

  rpc_server.controller_name_parser:
    class: Bankiru\Api\Rpc\Controller\RpcControllerNameParser
    arguments:
    - "@kernel"

  rpc_server.router.resolver:
    class: Bankiru\Api\Rpc\Routing\LoaderResolver

  rpc_server.router.collection:
    class: Bankiru\Api\Rpc\Routing\RouterCollection

  rpc_server.router.loader.file:
    abstract: true
    class: Bankiru\Api\Rpc\Routing\Loader\FileLoader
    calls:
    - [ "setResolver", ["@rpc_server.router.resolver"]]

  rpc_server.router.loader.yaml:
    class: Bankiru\Api\Rpc\Routing\Loader\YamlLoader
    parent: rpc_server.router.loader.file
    arguments:
    - "@file_locator"
    tags:
    - { name: rpc.route_loader }

  rpc_server.router.loader.annotation_class:
    class: Bankiru\Api\Rpc\Routing\Loader\AnnotationClassLoader
    arguments:
    - "@annotation_reader"
    tags:
    - { name: rpc.route_loader }

  rpc_server.router.loader.annotation_file:
    class: Bankiru\Api\Rpc\Routing\Loader\AnnotationFileLoader
    parent: rpc_server.router.loader.file
    arguments:
    - "@file_locator"
    - "@rpc_server.router.loader.annotation_class"
    tags:
    - { name: rpc.route_loader }

  rpc_server.router.loader.annotation_directory:
    class: Bankiru\Api\Rpc\Routing\Loader\AnnotationDirectoryLoader
    parent: rpc_server.router.loader.annotation_file
    tags:
    - { name: rpc.route_loader }
